<?php

namespace UKMNorge\RSVPBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends EntityRepository
{
	public function getCount( $event, $status = 'yes' ) {
		$query = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
		    ->where('r.status = :status')
		    ->andWhere('r.event = :event')
		    ->setParameter('status', $status)
		    ->setParameter('event', $event)
		    ->getQuery();
		
		$result = $query->getSingleResult();
		if( is_array( $result ) ) {
			return (int) $result[1];
		}
		return (int) $result;
	}
}
