services:
    ukmrsvp.event:
        class: UKMNorge\RSVPBundle\Services\EventService
        arguments: ["@service_container", "@router"]
        scope: request

    ukmrsvp.response:
        class: UKMNorge\RSVPBundle\Services\ResponseService
        arguments: ["@service_container", "@router"]
        scope: request

    ukmrsvp.waiting:
        class: UKMNorge\RSVPBundle\Services\WaitingService
        arguments: ["@service_container", "@router"]
        scope: request
